### ISSUE TITLE
Add Java Cryptography Extension - is unnecessary fuss in 1.8u192

### ISSUE THREAD

**Issue by hazartilirot** [simplyi/SpringCloudVideoCourse#11]
Well, I'm implementing the project on 19th Java, I couldn't have figured out why I am unable to find a link to download a file, as it turned out it is enabled by default starting from **8u161**

**Unlimited cryptography enabled by default**

The JDK uses the Java Cryptography Extension (JCE) Jurisdiction Policy files to configure cryptographic algorithm restrictions. Previously, the Policy files in the JDK placed limits on various algorithms. This release ships with both the limited and unlimited jurisdiction policy files, with unlimited being the default. The behavior can be controlled via the new 'crypto.policy' Security property found in the /lib/java.security file. Please refer to that file for more information on this property.

https://www.oracle.com/java/technologies/javase/8u161-relnotes.html#JDK-8170157

as for the **bootstrap.properties** it's also irrelevant already since the latest Spring Boot natively supports the parameters.

**Comment by hazartilirot** [comment]
There might also be an issue.... I decided to go with **users-ws.yml** therefore the whole password and {ciher} must be used with single-quotes. I have spent an hour figuring out what the heck.

here is my **users-ws.yml**
```
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photoapp
    username: root
    password: '{cipher}0b29caf0511052bc1c89e3d00feda309dd1fbcdf67b981eb2c91c969be6c662f'
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
```
