### ISSUE TITLE
Configure Project to use resilience4j Circuit Breaker - Feign

### ISSUE THREAD

**Issue by hazartilirot** [simplyi/SpringCloudVideoCourse#13]
Hi there. 

Actually, you almost don't need **resilience4j**. I have seen the latest Sergey's [implementation](https://github.com/simplyi/SpringCloudVideoCourse/blob/resilience4j-SpringBoot-3/PhotoAppApiUsers/src/main/java/com/appsdeveloperblog/photoapp/api/users/data/AlbumsServiceClient.java), but I decided to stick to what I had seen in the video with **Hystrix**

**pom.xml**
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>4.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
        </dependency>
```

Then, you need to enable fallback as it is [suggested](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#spring-cloud-feign-circuitbreaker) in the video though it has slightly different parameters:

In the **application.properties** / **application.yml** of the **PhotoAppApiUsers** set the following:
```
spring:  
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
```
I would also suggest switching to the **ERROR** mode.
```
logging:
  level:
    com:
      appsdeveloperblog:
        photoapp:
          api:
            users:
              client:
                AlbumsServiceClient: ERROR
```
I couldn't have figured out as to why I see an exception. The result was completely different from what Sergey gets in the video. 

<img width="2056" alt="Screenshot 2023-04-10 at 09 48 02" src="https://user-images.githubusercontent.com/1349977/230865415-bdfb59e4-9097-4f05-8271-3a6fe57639dd.png">

Finally, when I change the DEBUG to ERROR mode my console is clean now.

The last step is quite the same as you see in the video.

```
@FeignClient(name = "albums-ws", fallback = AlbumsFallback.class)
public interface AlbumsServiceClient {

    @GetMapping("/users/{id}/albums")
    List<AlbumResponseModel> getAlbums(@PathVariable String id);
}

@Component
class AlbumsFallback implements AlbumsServiceClient {

    @Override
    public List<AlbumResponseModel> getAlbums(String id) {
        return new ArrayList<>();
    }
}
```
