### ISSUE TITLE
Run RabbitMQ within a docker container.

### ISSUE THREAD

**Issue by hazartilirot** [simplyi/SpringCloudVideoCourse#8]
Well, it's not an issue, but a simple message to make your life easier. 

`docker-compose up -d `

**compose.yml**

```
version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.12.0-beta.5-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
```

[the latest RabbitMQ docker container](https://hub.docker.com/_/rabbitmq)

and 
**application.yml**
```
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
```
